name: CI/CD for Microservices Blog Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Install Dependencies and Build Each Service
      run: |
        cd backend/userService
        npm ci
        npm run build || echo "No build script found for userService"
        cd ../productService
        npm ci
        npm run build || echo "No build script found for productService"
        cd ../orderService
        npm ci
        npm run build || echo "No build script found for ordertService"

        cd ../../api-gateway
        npm ci
        npm run build || echo "No build script found for gateway"

    - name: Build & Push User Service
      run: |
        docker build -t aadilnv/ecommerce-user:latest backend/userService
        docker push aadilnv/ecommerce-user:latest

    - name: Build & Push Product Service
      run: |
        docker build -t aadilnv/ecommerce-product:latest backend/productService
        docker push aadilnv/ecommerce-product:latest

    - name: Build & Push Order Service
      run: |
        docker build -t aadilnv/ecommerce-order:latest backend/orderService
        docker push aadilnv/ecommerce-order:latest

    - name: Build & Push API Gateway
      run: |
        docker build -t aadilnv/ecommerce-gateway:latest ./api-gateway
        docker push aadilnv/ecommerce-gateway:latest
