name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Replace with your default branch if different
  pull_request:
    branches:
      - main # Replace with your default branch if different

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Run tests
      run: npm test

  build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 27017:27017
          - 5672:5672
          - 15672:15672

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for services to be available
      run: sleep 30

    - name: Run application tests
      run: |
        # Add commands to test your application if needed
        echo "Running application tests..."

    - name: Stop and remove containers
      run: docker-compose -f docker-compose.yml down
